### ISSUE TITLE
Roadmap to 4.0

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataNewsBundle#777]
## Feature Request

I want keep this bundle alive. It is not much work to do for 4.0 release. I can make it in this week. 

TODO:
- [ ] Changes in 3.x branch
    - [x] #771
    - [x] #773  
    - [ ] Close API
    - [ ] #675
    - [ ] #727
    - [ ] Move config from xml to php
    - [x] #779
- [ ] Changes in 4.x branch
    - [ ] Remove deprecations
    - [ ] Close API and add type hints 
    - [ ] #567
    - [x] #780
    - [ ] Resolve breadcrumb block problem
    - [ ] Update dependencies

**Comment by VincentLanglet** [comment]
We planned to add phpstan/psalm to all the project before a new major version.

But if we plan to release a new major, IMHO the abandoned keyword should be drop.
